### ISSUE TITLE
Translation buttons not working

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-prayer-campaigns#107]
![image](https://user-images.githubusercontent.com/24901539/188463455-4dabd1bc-454d-4486-80b0-99798ce2340f.png)

**Comment by corsacca** [comment]
And wondering if this section is needed

**Comment by squigglybob** [comment]
huh, that's strange that the buttons aren't working. They were working a moment ago 🙂

**Comment by squigglybob** [comment]
probably not needed for most porches, the location and people name might be needed for the ramadan template

**Comment by squigglybob** [comment]
@corsacca hmmm, they're working for me.... famous words I know...

could you check that the `dt_options.js` file loaded correctly on that admin page? The code to open the modal is at the top of that file

**Comment by corsacca** [comment]
this atr is empty
![image](https://user-images.githubusercontent.com/24901539/188829393-bff8e94d-f5e4-48dc-8898-77b2af909c0f.png)

**Comment by corsacca** [comment]
The other buttons on the page work.
