### ISSUE TITLE
Version Number

### ISSUE THREAD

**Issue by olsonsp4c** [DiscipleTools/disciple-tools-prayer-campaigns#11]
Hello - I believe that, when the latest release was pushed, the version number may not have been updated in the file read by WordPress as it keeps saying I need to update when I already have. thanks!

Scott

**Comment by corsacca** [comment]
Thanks @olsonsp4c !
The 1.3 release didn't create like i expected it to. Should be fixed now.

**Comment by olsonsp4c** [comment]
Thank you!
