### ISSUE TITLE
new subscribed prayer notifications not having the email verified toggle flipped

### ISSUE THREAD

**Issue by squigglybob** [DiscipleTools/disciple-tools-prayer-campaigns#148]
## New subscriptions not email verified

On first signing up for ongoing daily prayer slots the current user experience is

* sign up on the porch home page
* system creates 90 notification in dt_records
* system sends email to user to verify email
* user verifies email
* user starts receiving notifications

If they resign up for a further 90 days at the end of the 90 days
* system creates 90 new notifications in dt_records
* but they have their email verification flag turned off
* user doesn't receive any more notifications until these are flipped to on

This would need an update in `add_subscriber_time()` to mark new notifications as verified if that subscriber has already been verified in the past.
we could then use the `wp_postmeta` table  value of contact_email_123_verified to store that the user has their email verified, and then reference this when adding new subscriber times.

## UX of email verification

Looking at the DB for subscibers who didn't have their emails verified there were 160 out of 500 users who hadn't verified their email addresses.
Looking at all of those ones they all looked like legit email addresses.

A lot of them were gmail ones, so could have had their emails filtered into spam or into an updates tab so that they missed them or something.

for now I have verified all subscriber times to unblock Jenny and any others who weren't receiving their emails.

This suggests that we may need to rethink the protection of that prayer time subscription form that doesn't require the user to do anything in their emails.

Maybe we could use a recaptcha or honeypot?

**Comment by squigglybob** [comment]
At the moment, I have changed this line of code on the live server, so it will get clobbered on the next update of the prayer campaigns plugin, so it would be good to have part of this issue's fix before we clobber that.

in dt-subscriptions.php

![image](https://user-images.githubusercontent.com/9816214/211059124-c154a635-c753-4ae1-a467-107b87998018.png)

**Comment by squigglybob** [comment]
@corsacca @ChrisChasm

**Comment by corsacca** [comment]
@squigglybob my local test have "value" being changed to 1 right after those records are created.
![image](https://user-images.githubusercontent.com/24901539/213151459-9de801f8-5bc2-4929-b5c8-158d255d847c.png)
