### ISSUE TITLE
Weird display on safari

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-prayer-campaigns#167]
Safari 16.3 on a MacBook Air.
<img width="362" alt="Screenshot 2023-03-18 at 8 42 09 AM" src="https://user-images.githubusercontent.com/24901539/226280571-b60d437c-1aea-4300-855d-98d9580da684.png">

Demo: https://ramadandemo.pray4movement.org/

**Comment by prykon** [comment]
Cannot reproduce on Safari 16.3 with MacBook Pro

<img width="401" alt="Screenshot 2023-04-13 at 13 39 08" src="https://user-images.githubusercontent.com/36511666/231827152-31333da2-85a7-408c-9244-
bea6a463d2fb.png">
