### ISSUE TITLE
Campaign Apps tile needs explaining

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-prayer-campaigns#24]
The tile and the icons are not very informative. And if you click the (?) icon, you are given a modal with nothing useful to explain what is and how to use the tile.

<img width="897" alt="Screen Shot 2022-05-03 at 14 22 17" src="https://user-images.githubusercontent.com/43966676/166542710-1288b643-0694-4c1d-b160-f290759132dd.png">

**Comment by corsacca** [comment]
This tile comes from the theme and now looks like this:
![image](https://user-images.githubusercontent.com/24901539/191237961-26927b9c-431a-48b5-ba12-b184ed77c24c.png)
