### ISSUE TITLE
Prayer Campaigns v4!

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-prayer-campaigns#282]
## Prayer campaigns v4, multiple prayer campaigns at the same time.

Have you ever wanted to have multiple prayer campaigns running at the same time?
Have you ever wanted to go back to old campaigns and see the stats or access the prayer fuel?

Lets say you have a ongoing prayer campaign with a landing page running at pray4france.com. Now you want to also run a separate campaign for easter, what do you do? Before you had to set up a new Disciple.Tools instance or turn your wordpress install into a multisite and create a new subsite. Now all you need to do is create a new campaign.

You'll be able to run multiple campaigns from the same place:
- pray4france.com/ongoing <- pray4france.com pointing to this one
- pray4france.com/easter2023
- pray4france.com/easter2024

## With this version you also get:
- Editing page content from the front end
- Custom fields in the sign up tool
- A campaign creator role for just managing certain campaigns
- A form for contacting the campaign admin

### Edit page content directly
![image](https://github.com/DiscipleTools/disciple-tools-prayer-campaigns/assets/24901539/31965167-8da9-4404-a667-c521f38b814f)

![image](https://github.com/DiscipleTools/disciple-tools-prayer-campaigns/assets/24901539/eae195bb-ea6a-4696-8085-bc11211b0938)

### Custom fields
Add custom text or checkbox fields

![image](https://github.com/DiscipleTools/disciple-tools-prayer-campaigns/assets/24901539/e8f696b8-02ce-4a5d-bb7e-70b4a1758d7e)

### Campaign creator role

Invite a user and give them the campaign creator role.
This new user will only have access to the campaigns their are assigned to.

![image](https://github.com/DiscipleTools/disciple-tools-prayer-campaigns/assets/24901539/5ddc5ae0-6fa8-4862-b051-b4317b6c4f22)

### The Contact Us page
![image](https://github.com/DiscipleTools/disciple-tools-prayer-campaigns/assets/24901539/8664fff9-f686-4316-84c6-63e98f39067b)
![image](https://github.com/DiscipleTools/disciple-tools-prayer-campaigns/assets/24901539/8bdcc81e-5947-4bbc-bd99-ed3e1b508607)

**Comment by micahmills** [comment]
This looks great, glad to see this go out
