### ISSUE TITLE
new instance wizard autolaunch

### ISSUE THREAD

**Issue by squigglybob** [DiscipleTools/disciple-tools-prayer-campaigns#39]
- [x] get signup theme styled
- [x] signup form styled
- [x] signup form with extra meta
- [x] adjust the process, so that users get to the prayer campaigns wizard as the first thing that they do
- [x] create a subdomain site instead of subdirectory at blah.p4m.org rather than blah.campaigns.p4m.org
- [x] filter subdomain names for obvious spam sites

**Comment by squigglybob** [comment]
If this can be reusable for other servers that would be good

**Comment by squigglybob** [comment]
create WP Engine server and install the necessary plugins to get campaigns and porch working

**Comment by squigglybob** [comment]
as it currently stands, the meta info only gets saved when a new user creates a multisite.
The meta goes into the `wp_signups` table when a new user signs up.

If an existing, signed in user creates a new site, they will fill out the extra meta info, but it won't get saved to the `wp_signups` table

**Comment by corsacca** [comment]
ask for name in sign up.

     WHen the user activates a campaigns instance
     call crm create/update contact record
        new contact if email not found
        update contact if email found
     user name, email,
     contact record
     - New Link field [] = campaign instance url
     - Comment with the reason
     - add email on new record
     - and name and prayer website to comments

**Comment by squigglybob** [comment]
@corsacca I've just taken the crm link thing out of this issue, so we can merge it in.
Then the CRM link can be a seperate issue

**Comment by corsacca** [comment]
Implemented.
