### ISSUE TITLE
missing translations

### ISSUE THREAD

**Issue by squigglybob** [DiscipleTools/disciple-tools-prayer-campaigns#89]
- [x] Home
- [x] Sign up
- [x] sign up to pray
- [x] view all
- [x] next month
- [x] hours
- [x] more hours to be covered
- [x] Read
- [x] on {date}
- [x] Recieve Pray4Movement Newsletter (email verification needed).
- [x] Everyday at 00:45 AM for 15 minutes until October 26

**Comment by corsacca** [comment]
@squigglybob i think all these are done

**Comment by squigglybob** [comment]
Hey @corsacca the translations all look good,

I think  they are all there except for "on {date}"

![image](https://user-images.githubusercontent.com/9816214/186379210-2d0cf1fc-278f-47cb-ad78-6f876de6e8d1.png)

**Comment by corsacca** [comment]
removed the "on"
